# .pre-commit-config.yaml
default_language_version:
  python: python3.12

repos:
  - repo: local
    hooks:
      # ---- Ruff (new CLI requires `check`) ----
      - id: ruff
        name: Ruff (system)
        entry: ruff check
        language: system
        types: [python]
        args: [--fix, --no-cache]

      - id: isort
        name: isort (system)
        entry: isort --profile black
        language: system
        types: [python]

      - id: black
        name: Black (system)
        entry: black
        language: system
        types: [python]

      # ---- Migration linter (SQLite + Multi-Bind) ----
      - id: alembic-lint
        name: Alembic Migration Linter (SQLite + Multi-Bind)
        entry: python -X utf8 tools/alembic_lint.py
        language: system
        pass_filenames: false

      # ---- Model vs migration drift check ----
      - id: flask-db-check
        name: Flask DB Check (model vs migration drift)
        entry: python -X utf8 tools/flask_db_check.py
        language: system
        pass_filenames: false
