repos:
  # 1) Ruff first
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.6
    hooks:
      - id: ruff
        args: [--fix]

  # 2) isort second
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort

  # 3) Black third
  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black
        language_version: python3.10

  # 4) Local hooks after formatters/linters
  - repo: local
    hooks:
      - id: flask-db-check
        name: Flask DB Check (model vs migration drift)
        entry: python hooks/flask_db_check.py
        language: system
        pass_filenames: false

      - id: flask-db-single-head
        name: Alembic Single Head Check
        entry: python hooks/flask_db_single_head.py
        language: system
        pass_filenames: false

      - id: flask-db-upgrade-live
        name: Alembic Live Upgrade (temp SQLite)
        entry: python hooks/flask_db_upgrade_live.py
        language: system
        pass_filenames: false
