repos:
  # Ruff pinned
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.6
    hooks:
      - id: ruff
        args: [--fix]

  # isort pinned
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort

  # Black pinned
  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black
        language_version: python3.10

  # Local hooks (Windows CMD form)
  - repo: local
    hooks:
      # ---- Migration linter (runs on changed migration files) ----
      - id: alembic-lint
        name: Alembic Migration Linter (SQLite + Multi-Bind)
        entry: cmd /c "set PYTHONUTF8=1&& python tools\\alembic_lint.py"
        language: system
        pass_filenames: false
        files: ^migrations/versions/.*\.py$
        stages: [pre-commit]

      # ---- DB health checks ----
      - id: flask-db-check
        name: Flask DB Check (model vs migration drift)
        entry: cmd /c "set FLASK_APP=app:create_app&& set PYTHONUTF8=1&& python hooks\\flask_db_check.py"
        language: system
        pass_filenames: false
        stages: [pre-commit]
