[tool.black]
line-length = 88
target-version = ["py310"]
include = '\.pyi?$'
extend-exclude = '''
^(venv|instance|app/uploads|uploads_investigations|migrations|migrations_examination|.*/generated/)/
'''

[tool.isort]
profile = "black"
py_version = 310
line_length = 88
known_first_party = ["app", "tests"]
extend_skip_glob = [
  "migrations/**",
  "migrations_examination/**",
  "instance/**",
  "venv/**",
  "app/uploads/**",
  "uploads_investigations/**",
  "**/generated/**"
]

[tool.ruff]
target-version = "py310"
line-length = 88
select = ["E", "F", "I", "UP"]
ignore = ["E203", "W503"]
exclude = [
  "venv",
  "instance",
  "app/uploads",
  "uploads_investigations",
  "migrations",
  "migrations_examination",
  "**/generated/"
]
