"""Add uploaded_files field to Case

Revision ID: 2b287b7412c6
Revises: ba6cd013fef1
Create Date: 2025-06-11 14:55:48.735469

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "2b287b7412c6"
down_revision = "ba6cd013fef1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("case", schema=None) as batch_op:
        batch_op.add_column(sa.Column("uploaded_files", sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("case", schema=None) as batch_op:
        batch_op.drop_column("uploaded_files")

    # ### end Alembic commands ###
