"""add tox_completed to case

Revision ID: 39caa26b164c
Revises: f28b14d743a3
Create Date: 2025-07-30 12:14:22.538909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39caa26b164c'
down_revision = 'f28b14d743a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tox_completed', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case', schema=None) as batch_op:
        batch_op.drop_column('tox_completed')

    # ### end Alembic commands ###