"""Add certificate_generated fields

Revision ID: 4c9783535cda
Revises: ae7f2538c432
Create Date: 2025-07-24 11:19:46.087007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c9783535cda'
down_revision = 'ae7f2538c432'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case', schema=None) as batch_op:
        batch_op.add_column(sa.Column('certificate_generated', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('certificate_generated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case', schema=None) as batch_op:
        batch_op.drop_column('certificate_generated_at')
        batch_op.drop_column('certificate_generated')

    # ### end Alembic commands ###