"""add temp_id to case

Revision ID: 643ed23634d2
Revises: 140c20192107
Create Date: 2025-07-23 06:18:34.625798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '643ed23634d2'
down_revision = '140c20192107'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case', schema=None) as batch_op:
        batch_op.add_column(sa.Column('temp_id', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case', schema=None) as batch_op:
        batch_op.drop_column('temp_id')

    # ### end Alembic commands ###