"""Add UploadedFile model and relationship

Revision ID: 692afd38ecd9
Revises: b8e1a2a825bd
Create Date: 2025-06-23 13:50:49.148738

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "692afd38ecd9"
down_revision = "b8e1a2a825bd"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "uploaded_file",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("case_id", sa.Integer(), nullable=False),
        sa.Column("filename", sa.String(length=256), nullable=False),
        sa.Column("upload_time", sa.DateTime(), nullable=False),
        sa.Column("uploader", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["case.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("uploaded_file")
    # ### end Alembic commands ###
