"""Add screen_name to User

Revision ID: 7878ed5481b8
Revises: 2b287b7412c6
Create Date: 2025-06-16 10:53:01.772891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7878ed5481b8'
down_revision = '2b287b7412c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('screen_name', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('screen_name')

    # ### end Alembic commands ###
