"""add tox flags to case

Revision ID: 7c3b2383fefe
Revises: e8b17c3ab556
Create Date: 2025-08-05 13:52:50.148117

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "7c3b2383fefe"
down_revision = "e8b17c3ab556"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("case", schema=None) as batch_op:
        batch_op.add_column(sa.Column("tox_ordered", sa.Boolean(), nullable=True))
        batch_op.add_column(
            sa.Column("tox_viewed_by_expert", sa.Boolean(), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("case", schema=None) as batch_op:
        batch_op.drop_column("tox_viewed_by_expert")
        batch_op.drop_column("tox_ordered")

    # ### end Alembic commands ###
