"""Add default_leiro_id to User

Revision ID: 8c0438cc3f16
Revises: 643ed23634d2
Create Date: 2025-07-23 15:23:24.889298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c0438cc3f16'
down_revision = '643ed23634d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('default_leiro_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_user_default_leiro_id', 'user', ['default_leiro_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('fk_user_default_leiro_id', type_='foreignkey')
        batch_op.drop_column('default_leiro_id')

    # ### end Alembic commands ###
