"""Add tovabbi adatok fields to Case (fixed)

Revision ID: 9d325130fcd5
Revises: bf2fa14f0a27
Create Date: 2025-07-02 09:05:32.881930

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "9d325130fcd5"
down_revision = "bf2fa14f0a27"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("case", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("beerk_modja", sa.String(length=32), nullable=True)
        )
        batch_op.drop_column("beerk_módja")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("case", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("beerk_módja", sa.VARCHAR(length=20), nullable=True)
        )
        batch_op.drop_column("beerk_modja")

    # ### end Alembic commands ###
