"""Add tox ordered boolean fields

Revision ID: 9e45caa35bb6
Revises: c967f2236eca
Create Date: 2025-07-02 14:36:05.653401

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "9e45caa35bb6"
down_revision = "c967f2236eca"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("case", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("alkohol_ver_ordered", sa.Boolean(), nullable=True)
        )
        batch_op.add_column(
            sa.Column("alkohol_vizelet_ordered", sa.Boolean(), nullable=True)
        )
        batch_op.add_column(
            sa.Column("alkohol_liquor_ordered", sa.Boolean(), nullable=True)
        )
        batch_op.add_column(
            sa.Column("egyeb_alkohol_ordered", sa.Boolean(), nullable=True)
        )
        batch_op.add_column(
            sa.Column("tox_gyogyszer_ver_ordered", sa.Boolean(), nullable=True)
        )
        batch_op.add_column(
            sa.Column("tox_gyogyszer_vizelet_ordered", sa.Boolean(), nullable=True)
        )
        batch_op.add_column(
            sa.Column("tox_gyogyszer_gyomor_ordered", sa.Boolean(), nullable=True)
        )
        batch_op.add_column(
            sa.Column("tox_gyogyszer_maj_ordered", sa.Boolean(), nullable=True)
        )
        batch_op.add_column(
            sa.Column("tox_kabitoszer_ver_ordered", sa.Boolean(), nullable=True)
        )
        batch_op.add_column(
            sa.Column("tox_kabitoszer_vizelet_ordered", sa.Boolean(), nullable=True)
        )
        batch_op.add_column(sa.Column("tox_cpk_ordered", sa.Boolean(), nullable=True))
        batch_op.add_column(
            sa.Column("tox_szarazanyag_ordered", sa.Boolean(), nullable=True)
        )
        batch_op.add_column(
            sa.Column("tox_diatoma_ordered", sa.Boolean(), nullable=True)
        )
        batch_op.add_column(sa.Column("tox_co_ordered", sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column("egyeb_tox_ordered", sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("case", schema=None) as batch_op:
        batch_op.drop_column("egyeb_tox_ordered")
        batch_op.drop_column("tox_co_ordered")
        batch_op.drop_column("tox_diatoma_ordered")
        batch_op.drop_column("tox_szarazanyag_ordered")
        batch_op.drop_column("tox_cpk_ordered")
        batch_op.drop_column("tox_kabitoszer_vizelet_ordered")
        batch_op.drop_column("tox_kabitoszer_ver_ordered")
        batch_op.drop_column("tox_gyogyszer_maj_ordered")
        batch_op.drop_column("tox_gyogyszer_gyomor_ordered")
        batch_op.drop_column("tox_gyogyszer_vizelet_ordered")
        batch_op.drop_column("tox_gyogyszer_ver_ordered")
        batch_op.drop_column("egyeb_alkohol_ordered")
        batch_op.drop_column("alkohol_liquor_ordered")
        batch_op.drop_column("alkohol_vizelet_ordered")
        batch_op.drop_column("alkohol_ver_ordered")

    # ### end Alembic commands ###
