"""add examinationcase table

Revision ID: a0c2905147be
Revises: a5044c447197
Create Date: 2025-08-07 13:36:31.799129

"""
from alembic import op, context
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0c2905147be'
down_revision = 'a5044c447197'
branch_labels = None
depends_on = None


def upgrade():
    # Guard: avoid running on the primary bind
    if context.get_tag_argument() != "examination":
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'examination_case',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('investigation_number', sa.String(length=20), nullable=False),
        sa.Column('type', sa.String(length=64), nullable=True),
        sa.Column('institution', sa.String(length=128), nullable=True),
        sa.Column('ordering_authority', sa.String(length=128), nullable=True),
        sa.Column('deceased_name', sa.String(length=128), nullable=True),
        sa.Column('date_of_birth', sa.Date(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('investigation_number')
    )
    # ### end Alembic commands ###


def downgrade():
    if context.get_tag_argument() != "examination":
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('examination_case')
    # ### end Alembic commands ###