"""Add recipient column to TaskMessage

Revision ID: a5044c447197
Revises: bde20535b015
Create Date: 2025-08-07 09:07:30.795784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5044c447197'
down_revision = 'bde20535b015'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recipient', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_message', schema=None) as batch_op:
        batch_op.drop_column('recipient')

    # ### end Alembic commands ###