"""add user session log model

Revision ID: af99da151777
Revises: 0eae546e0107
Create Date: 2025-08-04 06:07:18.051647

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "af99da151777"
down_revision = "0eae546e0107"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_session_log",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("path", sa.String(length=255), nullable=True),
        sa.Column("event_type", sa.String(length=64), nullable=True),
        sa.Column("element", sa.String(length=128), nullable=True),
        sa.Column("value", sa.Text(), nullable=True),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=True),
        sa.Column("extra", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_session_log")
    # ### end Alembic commands ###
