"""Add tox_orders column to Case

Revision ID: b8e1a2a825bd
Revises: 7878ed5481b8
Create Date: 2025-06-18 15:33:25.982535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8e1a2a825bd'
down_revision = '7878ed5481b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tox_orders', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case', schema=None) as batch_op:
        batch_op.drop_column('tox_orders')

    # ### end Alembic commands ###
