"""Add extended forensic case fields

Revision ID: ba6cd013fef1
Revises: f02f2c72c9b9
Create Date: 2025-06-11 14:20:23.071120

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "ba6cd013fef1"
down_revision = "f02f2c72c9b9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("case", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("deceased_name", sa.String(length=128), nullable=True)
        )
        batch_op.add_column(sa.Column("case_type", sa.String(length=64), nullable=True))
        batch_op.add_column(
            sa.Column("institution_name", sa.String(length=128), nullable=True)
        )
        batch_op.add_column(
            sa.Column("external_case_number", sa.String(length=64), nullable=True)
        )
        batch_op.add_column(sa.Column("birth_date", sa.Date(), nullable=True))
        batch_op.add_column(
            sa.Column("registration_time", sa.DateTime(), nullable=True)
        )
        batch_op.add_column(sa.Column("deadline", sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column("expert_1", sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column("expert_2", sa.String(length=128), nullable=True))
        batch_op.add_column(
            sa.Column("describer", sa.String(length=128), nullable=True)
        )
        batch_op.drop_column("created_at")
        batch_op.drop_column("year")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("case", schema=None) as batch_op:
        batch_op.add_column(sa.Column("year", sa.INTEGER(), nullable=False))
        batch_op.add_column(
            sa.Column(
                "created_at",
                sa.DATETIME(),
                server_default=sa.text("(CURRENT_TIMESTAMP)"),
                nullable=True,
            )
        )
        batch_op.drop_column("describer")
        batch_op.drop_column("expert_2")
        batch_op.drop_column("expert_1")
        batch_op.drop_column("deadline")
        batch_op.drop_column("registration_time")
        batch_op.drop_column("birth_date")
        batch_op.drop_column("external_case_number")
        batch_op.drop_column("institution_name")
        batch_op.drop_column("case_type")
        batch_op.drop_column("deceased_name")

    # ### end Alembic commands ###
