"""add started_by_expert to case

Revision ID: bde20535b015
Revises: abcd1234ef56
Create Date: 2025-08-06 11:42:55.061333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bde20535b015'
down_revision = 'abcd1234ef56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case', schema=None) as batch_op:
        batch_op.add_column(sa.Column('started_by_expert', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case', schema=None) as batch_op:
        batch_op.drop_column('started_by_expert')

    # ### end Alembic commands ###