"""Add tovabbi adatok fields to Case

Revision ID: bf2fa14f0a27
Revises: 692afd38ecd9
Create Date: 2025-07-02 08:24:56.369613

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "bf2fa14f0a27"
down_revision = "692afd38ecd9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("case", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("beerk_módja", sa.String(length=20), nullable=True)
        )
        batch_op.add_column(sa.Column("poszeidon", sa.String(length=64), nullable=True))
        batch_op.add_column(
            sa.Column("lanykori_nev", sa.String(length=128), nullable=True)
        )
        batch_op.add_column(
            sa.Column("szul_hely", sa.String(length=128), nullable=True)
        )
        batch_op.add_column(sa.Column("taj_szam", sa.String(length=16), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("case", schema=None) as batch_op:
        batch_op.drop_column("taj_szam")
        batch_op.drop_column("szul_hely")
        batch_op.drop_column("lanykori_nev")
        batch_op.drop_column("poszeidon")
        batch_op.drop_column("beerk_módja")

    # ### end Alembic commands ###
