"""drop old investigation tables

Revision ID: 310105dd28d2
Revises: 0447aeda5a95
Create Date: 2025-09-01 09:20:30.284772

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "310105dd28d2"
down_revision = "0447aeda5a95"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("investigation_note")
    op.drop_table("investigation")
    op.drop_table("investigation_attachment")
    op.drop_table("investigation_change_log")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "investigation_change_log",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("investigation_id", sa.INTEGER(), nullable=False),
        sa.Column("field_name", sa.VARCHAR(length=64), nullable=False),
        sa.Column("old_value", sa.TEXT(), nullable=True),
        sa.Column("new_value", sa.TEXT(), nullable=True),
        sa.Column("edited_by", sa.INTEGER(), nullable=False),
        sa.Column("timestamp", sa.DATETIME(), nullable=True),
        sa.ForeignKeyConstraint(
            ["investigation_id"],
            ["investigation.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "investigation_attachment",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("investigation_id", sa.INTEGER(), nullable=False),
        sa.Column("filename", sa.VARCHAR(length=255), nullable=False),
        sa.Column("category", sa.VARCHAR(length=64), nullable=True),
        sa.Column("uploaded_by", sa.INTEGER(), nullable=False),
        sa.Column("uploaded_at", sa.DATETIME(), nullable=True),
        sa.ForeignKeyConstraint(
            ["investigation_id"],
            ["investigation.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "investigation",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("case_number", sa.VARCHAR(length=16), nullable=False),
        sa.Column("external_case_number", sa.VARCHAR(length=64), nullable=True),
        sa.Column("other_identifier", sa.VARCHAR(length=64), nullable=True),
        sa.Column("subject_name", sa.VARCHAR(length=128), nullable=False),
        sa.Column("maiden_name", sa.VARCHAR(length=128), nullable=True),
        sa.Column("investigation_type", sa.VARCHAR(length=64), nullable=True),
        sa.Column("mother_name", sa.VARCHAR(length=128), nullable=False),
        sa.Column("birth_place", sa.VARCHAR(length=128), nullable=False),
        sa.Column("birth_date", sa.DATE(), nullable=False),
        sa.Column("taj_number", sa.VARCHAR(length=16), nullable=False),
        sa.Column("residence", sa.VARCHAR(length=255), nullable=False),
        sa.Column("citizenship", sa.VARCHAR(length=255), nullable=False),
        sa.Column("institution_name", sa.VARCHAR(length=128), nullable=False),
        sa.Column("registration_time", sa.DATETIME(), nullable=True),
        sa.Column("deadline", sa.DATETIME(), nullable=True),
        sa.Column("expert1_id", sa.INTEGER(), nullable=True),
        sa.Column("expert2_id", sa.INTEGER(), nullable=True),
        sa.Column("describer_id", sa.INTEGER(), nullable=True),
        sa.Column("assignment_type", sa.VARCHAR(length=32), nullable=True),
        sa.Column("assigned_expert_id", sa.INTEGER(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "investigation_note",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("investigation_id", sa.INTEGER(), nullable=False),
        sa.Column("author_id", sa.INTEGER(), nullable=False),
        sa.Column("text", sa.TEXT(), nullable=False),
        sa.Column("timestamp", sa.DATETIME(), nullable=True),
        sa.ForeignKeyConstraint(
            ["investigation_id"],
            ["investigation.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###
