name: CI

on:
  push:
  pull_request:

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: pip

      - name: Install dependencies (prod + dev)
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f requirements-dev.txt ]; then
            pip install -r requirements-dev.txt
          else
            pip install pytest pytest-xdist coverage ruff isort black iniconfig pluggy
          fi

      - name: Ruff (lint)
        run: ruff .

      - name: Black (check)
        run: black --check .

      - name: isort (check-only)
        run: isort --check-only .

      - name: Pytest (quiet)
        run: python -m pytest -q
