name: CI

on:
  push:
  pull_request:

jobs:
  lint-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install dependencies (dev + prod)
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements-dev.txt ]; then
            python -m pip install -r requirements-dev.txt
          fi
          python -m pip install -r requirements.txt
          # Backfill CI tooling in case requirements-dev.txt has win32 markers
          python -m pip install ruff isort black pytest

      - name: Lint (ruff)
        run: ruff .

      - name: Format check (black)
        run: black --check .

      - name: Import order (isort)
        run: isort --check-only .

      - name: Run tests
        run: python -m pytest -q
