name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements-dev.txt ]; then
            python -m pip install -r requirements-dev.txt
          fi
          python -m pip install -r requirements.txt

      - name: Run Ruff
        run: ruff .

      - name: Run Black (check)
        run: black --check .

      - name: Run isort (check-only)
        run: isort --check-only .

      - name: Run pytest
        run: python -m pytest -q
