name: CI

on:
  push:
  pull_request:

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Ruff (lint)
        run: ruff . || ruff check .

      - name: Black (check)
        run: black --check .

      - name: isort (check-only)
        run: isort --check-only .

      - name: Pytest (quiet)
        run: pytest -q
